@server = http://localhost:4004

@credentials = Authorization: Basic P029977:

###V2
GET {{server}}/v2/mdg/RequestValues
{{credentials}}

###V2
GET {{server}}/mdg/RequestValues
{{credentials}}

### ValueHelp collection
GET {{server}}/mdg/VH_CustomerGen?$top=5
{{credentials}}

### Metadata V2
GET {{server}}/v2/mdg/$metadata
{{credentials}}

### getFormDefinition (REQUESTER)
POST {{server}}/mdg/getFormDefinition
{{credentials}}
Content-Type: application/json

{
  "processCode": "CUSTOMER_CREATION",
  "countryCode": "CL",
  "roleCode": "REQUESTER"
}

### getFormDefinition (APPROVER)
POST {{server}}/mdg/getFormDefinition
{{credentials}}
Content-Type: application/json

{
  "processCode": "CUSTOMER_CREATION",
  "countryCode": "CL",
  "roleCode": "APPROVER"
}

### getAvailableProcesses
POST {{server}}/mdg/getAvailableProcesses
{{credentials}}
Content-Type: application/json

{"countryCode": "CL", "frontCode": "MTO"}


### CREATE
POST {{server}}/mdg/Request
{{credentials}}
Content-Type: application/json

{"PROCESS_ID":"941f1e91-1c71-5e5d-935e-d5e7a9bc9449","COUNTRY_CODE":"CL","SUBJECT_TYPE":"CUSTOMER","STATUS":"DRAFT","FRONT_CODE":"MTO"}

### metadata
POST {{server}}/mdg/fetchS4Metadata
Content-Type: application/json

{
  "servicePath": "/sap/opu/odata/sap/ZCDS_CLIENTES_GEN_CDS"
}